-- Phase 30: additive long-form novel memory foundation.
-- MySQL remains canonical; vector and graph indexes are rebuildable projections.

CREATE TABLE IF NOT EXISTS ai_project_memory_fact (
    fact_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    generation_id BIGINT NULL,
    document_generation_id BIGINT NULL,
    fact_type VARCHAR(60) NOT NULL,
    subject_entity_id BIGINT NULL,
    predicate VARCHAR(120) NULL,
    object_value LONGTEXT NULL,
    canonical_key VARCHAR(512) NOT NULL,
    statement TEXT NOT NULL,
    normalized_json JSON NULL,
    lifecycle_status VARCHAR(40) NOT NULL DEFAULT 'PENDING_REVIEW',
    confidence DECIMAL(5,4) NULL,
    importance DECIMAL(5,4) NULL,
    valid_from_chapter_no INT NULL,
    valid_to_chapter_no INT NULL,
    recorded_from_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_to_at DATETIME NULL,
    source_kind VARCHAR(40) NOT NULL,
    extractor_version VARCHAR(64) NULL,
    supersedes_fact_id BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_project_memory_fact_scope (user_id, project_id, work_id, fact_type, lifecycle_status),
    INDEX idx_ai_project_memory_fact_key (user_id, project_id, work_id, canonical_key, recorded_to_at),
    INDEX idx_ai_project_memory_fact_validity (work_id, valid_from_chapter_no, valid_to_chapter_no),
    INDEX idx_ai_project_memory_fact_generation (generation_id, document_generation_id, lifecycle_status),
    INDEX idx_ai_project_memory_fact_supersedes (supersedes_fact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='bitemporal canonical and candidate project memory facts';

CREATE TABLE IF NOT EXISTS ai_project_memory_evidence (
    evidence_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    fact_id BIGINT NOT NULL,
    generation_id BIGINT NULL,
    document_generation_id BIGINT NULL,
    chapter_id BIGINT NULL,
    section_id BIGINT NULL,
    scene_id BIGINT NULL,
    quote_text TEXT NULL,
    quote_hash VARCHAR(128) NULL,
    start_offset INT NULL,
    end_offset INT NULL,
    evidence_role VARCHAR(40) NOT NULL DEFAULT 'SUPPORTS',
    confidence DECIMAL(5,4) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_project_memory_evidence_fact (fact_id, status, evidence_id),
    INDEX idx_ai_project_memory_evidence_scope (user_id, project_id, work_id, status),
    INDEX idx_ai_project_memory_evidence_chapter (generation_id, chapter_id, scene_id, status),
    INDEX idx_ai_project_memory_evidence_document (document_generation_id, section_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='traceable source evidence for long-form memory facts';

CREATE TABLE IF NOT EXISTS ai_project_memory_entity_alias (
    alias_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    entity_id BIGINT NOT NULL,
    alias VARCHAR(255) NOT NULL,
    normalized_alias VARCHAR(255) NOT NULL,
    valid_from_chapter_no INT NULL,
    valid_to_chapter_no INT NULL,
    confidence DECIMAL(5,4) NULL,
    source_evidence_id BIGINT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_project_memory_alias_lookup (user_id, project_id, work_id, normalized_alias, status),
    INDEX idx_ai_project_memory_alias_entity (entity_id, status, valid_from_chapter_no),
    INDEX idx_ai_project_memory_alias_evidence (source_evidence_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='chapter-aware aliases for canonical story entities';

CREATE TABLE IF NOT EXISTS ai_project_summary_node (
    summary_node_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    generation_id BIGINT NULL,
    document_generation_id BIGINT NULL,
    node_type VARCHAR(30) NOT NULL,
    parent_node_id BIGINT NULL,
    range_from_chapter INT NULL,
    range_to_chapter INT NULL,
    summary_text LONGTEXT NOT NULL,
    summary_json JSON NULL,
    source_hash VARCHAR(128) NOT NULL,
    summary_version INT NOT NULL DEFAULT 1,
    token_count INT NOT NULL DEFAULT 0,
    child_count INT NOT NULL DEFAULT 0,
    coverage_json JSON NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    recorded_from_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_to_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_project_summary_scope (user_id, project_id, work_id, node_type, status),
    INDEX idx_ai_project_summary_parent (parent_node_id, status, summary_node_id),
    INDEX idx_ai_project_summary_range (work_id, range_from_chapter, range_to_chapter, status),
    INDEX idx_ai_project_summary_generation (generation_id, document_generation_id, status),
    UNIQUE KEY uk_ai_project_summary_source_version (user_id, project_id, work_id, node_type, source_hash, summary_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='hierarchical scene to work summaries with corpus coverage';

CREATE TABLE IF NOT EXISTS ai_project_summary_evidence (
    summary_evidence_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    summary_node_id BIGINT NOT NULL,
    evidence_id BIGINT NULL,
    child_summary_node_id BIGINT NULL,
    relation_type VARCHAR(40) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ai_project_summary_evidence_node (summary_node_id, relation_type, summary_evidence_id),
    INDEX idx_ai_project_summary_evidence_source (evidence_id, child_summary_node_id),
    INDEX idx_ai_project_summary_evidence_scope (user_id, project_id, work_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='summary links to source evidence and child summaries';
