-- Phase 15: durable AI chat runs and active agent-runtime eval cases.
-- Usage:
--   mysql -h127.0.0.1 -uroot -p novel_analyzer < backend/sql/mysql/phase15-ai-chat-run-production.sql

CREATE TABLE IF NOT EXISTS ai_chat_run (
    run_id VARCHAR(64) PRIMARY KEY COMMENT 'stable chat run id',
    user_id BIGINT NOT NULL COMMENT 'owner user id',
    project_id BIGINT NULL COMMENT 'optional writing project id',
    conversation_id VARCHAR(80) NOT NULL COMMENT 'durable chat conversation id',
    question MEDIUMTEXT COMMENT 'user question snapshot',
    request_json JSON COMMENT 'full request payload',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING / RUNNING / ANSWERED / FAILED / CANCELLED',
    progress_phase VARCHAR(40) COMMENT 'current phase key',
    progress_message VARCHAR(500) COMMENT 'operator-facing progress',
    answer MEDIUMTEXT COMMENT 'final answer',
    result_json JSON COMMENT 'final structured result',
    trace_id VARCHAR(80) COMMENT 'worker trace id',
    source_count INT NOT NULL DEFAULT 0 COMMENT 'visible source count',
    error_message VARCHAR(1000) COMMENT 'last error',
    cancel_requested TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'cancel requested by user',
    retry_count INT NOT NULL DEFAULT 0 COMMENT 'retry count',
    max_retries INT NOT NULL DEFAULT 3 COMMENT 'max retry budget',
    queued_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'queued time',
    started_at DATETIME NULL COMMENT 'started time',
    finished_at DATETIME NULL COMMENT 'finished time',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    deleted TINYINT DEFAULT 0 COMMENT 'logic delete flag',
    INDEX idx_ai_chat_run_user_conversation (user_id, conversation_id, deleted, queued_at),
    INDEX idx_ai_chat_run_user_status (user_id, status, deleted, queued_at),
    INDEX idx_ai_chat_run_project (project_id, deleted, queued_at),
    INDEX idx_ai_chat_run_trace (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='durable AI chat run';

INSERT INTO ai_eval_golden_case(
    suite_name, case_key, case_type, question, request_json,
    expected_intent, expected_answer_mode, expected_sub_intents,
    relevant_source_ids, required_source_types, forbidden_claims,
    answer_rubric, retrieval_thresholds, status, tags, notes, deleted
)
VALUES
('agent-runtime', 'agent-runtime-market-top30-urban', 'market_scan',
 '男频都市脑洞新书榜整体30名趋势如何，类似题材有哪些？',
 '{"question":"男频都市脑洞新书榜整体30名趋势如何，类似题材有哪些？","mode":"research","reasoningMode":"deep","limits":{"rankLimit":30,"evidenceLimit":30}}',
 'market_scan', NULL, '["market_scan"]', '[]', '["RANK"]', '["世界首富","无敌修仙"]',
 '{"required_terms":["Top30","都市脑洞","趋势","类似题材"],"required_trace_nodes":["execute_tools","supervise_evidence","compose_answer"],"required_tools":["rank.lookup"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","rank","top30"]',
 'Top30 market scan runtime smoke case', 0),
('agent-runtime', 'agent-runtime-mixed-outline-outsourcing', 'mixed_creation',
 '现在我要写底层职业都市脑洞，诸天万界外包做特效，三端一体金手指，请结合榜单给完整大纲。',
 '{"question":"现在我要写底层职业都市脑洞，诸天万界外包做特效，三端一体金手指，请结合榜单给完整大纲。","mode":"research","reasoningMode":"deep","limits":{"rankLimit":30,"evidenceLimit":30}}',
 'mixed_creation_research', NULL, '["market_scan","outline_building","inspiration_expand"]', '[]', '["RANK"]', '["只复制榜一","无法判断"]',
 '{"required_terms":["底层职业","诸天万界","三端一体","大纲"],"required_trace_nodes":["route_experts","compose_answer"],"required_tools":["rank.lookup","skill.lookup"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","mixed","outline"]',
 'Reported production mixed creation prompt', 0),
('agent-runtime', 'agent-runtime-followup-memory-outline', 'conversation_followup',
 '给出完整的大纲设计',
 '{"question":"给出完整的大纲设计","mode":"research","reasoningMode":"deep","conversationId":"eval-conv-followup","contextSummary":"最近用户目标：底层职业都市脑洞，诸天万界外包做特效，三端一体金手指。","history":[{"role":"user","content":"我要写底层职业都市脑洞，诸天万界外包做特效。"},{"role":"assistant","content":"已确认设定：影视特效底层职业、三端一体系统、外包交付循环。"}],"limits":{"rankLimit":30,"evidenceLimit":20}}',
 'outline_building', NULL, '["outline_building"]', '[]', '[]', '["请选择书籍","candidates_required"]',
 '{"required_terms":["大纲","三端一体","外包"],"required_trace_nodes":["assemble_context","compose_answer"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","memory","followup"]',
 'Short follow-up should use conversation context', 0),
('agent-runtime', 'agent-runtime-skill-memory-budget', 'mixed_creation',
 '基于我项目里的设定，补一个前三章细纲，并指出读者毒点。',
 '{"question":"基于我项目里的设定，补一个前三章细纲，并指出读者毒点。","mode":"research","reasoningMode":"deep","projectId":1,"conversationId":"eval-project-conv","contextSummary":"项目设定：都市特效外包，主角是底层特效师。","limits":{"rankLimit":10,"evidenceLimit":20}}',
 'mixed_creation_research', NULL, '["chapter_outline","reader_risk"]', '[]', '[]', '["tool call budget exhausted"]',
 '{"required_terms":["前三章","毒点","读者"],"required_tools":["skill.lookup","memory.project_context"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","skill","memory"]',
 'Required skill/memory tools should not be starved by rank tools', 0),
('agent-runtime', 'agent-runtime-book-breakdown', 'book_breakdown',
 '拆解一本都市脑洞榜单书的开篇卖点、爽点节奏和可借鉴结构。',
 '{"question":"拆解一本都市脑洞榜单书的开篇卖点、爽点节奏和可借鉴结构。","mode":"research","reasoningMode":"fast","limits":{"candidateLimit":5,"chapterLimit":5,"evidenceLimit":15}}',
 'book_breakdown', NULL, '["book_breakdown"]', '[]', '["CHAPTER","RANK"]', '["没有依据"]',
 '{"required_terms":["开篇","卖点","节奏"],"required_trace_nodes":["execute_tools","compose_answer"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","book"]',
 'Book breakdown route smoke case', 0),
('agent-runtime', 'agent-runtime-character-worldbuilding', 'creative_generation',
 '给这个诸天外包特效题材设计主角、女主、竞争管理员和第一卷世界观规则。',
 '{"question":"给这个诸天外包特效题材设计主角、女主、竞争管理员和第一卷世界观规则。","mode":"research","reasoningMode":"deep","contextSummary":"题材：诸天万界外包做特效，三端一体系统。","limits":{"evidenceLimit":10}}',
 'mixed_creation_research', NULL, '["character_design","worldbuilding"]', '[]', '[]', '["模板化"]',
 '{"required_terms":["主角","女主","竞争管理员","世界观"],"required_trace_nodes":["route_experts","compose_answer"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","character","worldbuilding"]',
 'Specialist routing smoke case', 0),
('agent-runtime', 'agent-runtime-revision-editor', 'revision',
 '这段开篇太慢，帮我按都市脑洞榜单节奏重写冲突推进建议。',
 '{"question":"这段开篇太慢，帮我按都市脑洞榜单节奏重写冲突推进建议。","mode":"research","reasoningMode":"deep","contextSummary":"开篇问题：系统解释过多，公共反应太晚。","limits":{"rankLimit":20,"evidenceLimit":20}}',
 'mixed_creation_research', NULL, '["revision","market_scan"]', '[]', '["RANK"]', '["泛泛而谈"]',
 '{"required_terms":["开篇","冲突","节奏","建议"],"required_tools":["rank.lookup","skill.lookup"]}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","revision","editor"]',
 'Revision plus market evidence case', 0),
('agent-runtime', 'agent-runtime-deep-model-cap', 'deep_answer',
 '深度模式下给出一份不少于三卷的完整商业化大纲。',
 '{"question":"深度模式下给出一份不少于三卷的完整商业化大纲。","mode":"research","reasoningMode":"deep","contextSummary":"题材：底层特效师，诸天外包，三端一体。","limits":{"rankLimit":30,"evidenceLimit":20}}',
 'outline_building', NULL, '["outline_building"]', '[]', '[]', '["回答过短","请选择作品"]',
 '{"required_terms":["第一卷","第二卷","第三卷"],"required_trace_nodes":["compose_answer"],"expect_no_local_final_cap":true}',
 '{"min_hit_rate_at_k":0.0,"min_context_recall_at_k":0.0}', 'ACTIVE', '["runtime","deep","token-cap"]',
 'Deep answer should avoid local truncation when runtime policy disables cap', 0)
ON DUPLICATE KEY UPDATE
    case_type = VALUES(case_type),
    question = VALUES(question),
    request_json = VALUES(request_json),
    expected_intent = VALUES(expected_intent),
    expected_answer_mode = VALUES(expected_answer_mode),
    expected_sub_intents = VALUES(expected_sub_intents),
    relevant_source_ids = VALUES(relevant_source_ids),
    required_source_types = VALUES(required_source_types),
    forbidden_claims = VALUES(forbidden_claims),
    answer_rubric = VALUES(answer_rubric),
    retrieval_thresholds = VALUES(retrieval_thresholds),
    status = 'ACTIVE',
    tags = VALUES(tags),
    notes = VALUES(notes),
    deleted = 0;
