CREATE TABLE IF NOT EXISTS ai_project_memory_fact (
    fact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    generation_id BIGINT, document_generation_id BIGINT, fact_type VARCHAR(60) NOT NULL,
    subject_entity_id BIGINT, predicate VARCHAR(120), object_value CLOB,
    canonical_key VARCHAR(512) NOT NULL, statement CLOB NOT NULL, normalized_json CLOB,
    lifecycle_status VARCHAR(40) NOT NULL DEFAULT 'PENDING_REVIEW',
    confidence DECIMAL(5,4), importance DECIMAL(5,4),
    valid_from_chapter_no INT, valid_to_chapter_no INT,
    recorded_from_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, recorded_to_at TIMESTAMP,
    source_kind VARCHAR(40) NOT NULL, extractor_version VARCHAR(64), supersedes_fact_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_project_memory_fact_scope ON ai_project_memory_fact(user_id, project_id, work_id, fact_type, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_ai_project_memory_fact_key ON ai_project_memory_fact(user_id, project_id, work_id, canonical_key, recorded_to_at);

CREATE TABLE IF NOT EXISTS ai_project_memory_evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    fact_id BIGINT NOT NULL, generation_id BIGINT, document_generation_id BIGINT,
    chapter_id BIGINT, section_id BIGINT, scene_id BIGINT, quote_text CLOB,
    quote_hash VARCHAR(128), start_offset INT, end_offset INT,
    evidence_role VARCHAR(40) NOT NULL DEFAULT 'SUPPORTS', confidence DECIMAL(5,4),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_project_memory_evidence_fact ON ai_project_memory_evidence(fact_id, status, evidence_id);

CREATE TABLE IF NOT EXISTS ai_project_memory_entity_alias (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    entity_id BIGINT NOT NULL, alias VARCHAR(255) NOT NULL, normalized_alias VARCHAR(255) NOT NULL,
    valid_from_chapter_no INT, valid_to_chapter_no INT, confidence DECIMAL(5,4),
    source_evidence_id BIGINT, status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_project_memory_alias_lookup ON ai_project_memory_entity_alias(user_id, project_id, work_id, normalized_alias, status);

CREATE TABLE IF NOT EXISTS ai_project_summary_node (
    summary_node_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    generation_id BIGINT, document_generation_id BIGINT, node_type VARCHAR(30) NOT NULL,
    parent_node_id BIGINT, range_from_chapter INT, range_to_chapter INT,
    summary_text CLOB NOT NULL, summary_json CLOB, source_hash VARCHAR(128) NOT NULL,
    summary_version INT NOT NULL DEFAULT 1, token_count INT NOT NULL DEFAULT 0,
    child_count INT NOT NULL DEFAULT 0, coverage_json CLOB,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    recorded_from_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, recorded_to_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase30_summary_source_version UNIQUE(user_id, project_id, work_id, node_type, source_hash, summary_version)
);
CREATE INDEX IF NOT EXISTS idx_ai_project_summary_scope ON ai_project_summary_node(user_id, project_id, work_id, node_type, status);
CREATE INDEX IF NOT EXISTS idx_ai_project_summary_parent ON ai_project_summary_node(parent_node_id, status, summary_node_id);

CREATE TABLE IF NOT EXISTS ai_project_summary_evidence (
    summary_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    summary_node_id BIGINT NOT NULL, evidence_id BIGINT, child_summary_node_id BIGINT,
    relation_type VARCHAR(40) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_project_summary_evidence_node ON ai_project_summary_evidence(summary_node_id, relation_type, summary_evidence_id);
