CREATE TABLE IF NOT EXISTS ai_project_document_batch (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL, manifest_hash VARCHAR(128) NOT NULL,
    parser_version VARCHAR(64) NOT NULL, status VARCHAR(40) NOT NULL,
    stage VARCHAR(40) NOT NULL, progress INT NOT NULL DEFAULT 0,
    total_files INT NOT NULL DEFAULT 0, stored_files INT NOT NULL DEFAULT 0,
    parsed_files INT NOT NULL DEFAULT 0, indexed_files INT NOT NULL DEFAULT 0,
    skipped_files INT NOT NULL DEFAULT 0, failed_files INT NOT NULL DEFAULT 0,
    pending_questions INT NOT NULL DEFAULT 0, total_bytes BIGINT NOT NULL DEFAULT 0,
    attempt INT NOT NULL DEFAULT 1, max_attempts INT NOT NULL DEFAULT 4,
    lease_owner VARCHAR(128), lease_expires_at TIMESTAMP, heartbeat_at TIMESTAMP,
    fencing_token BIGINT NOT NULL DEFAULT 0, cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    error_code VARCHAR(64), error_summary VARCHAR(1000), completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase29_batch_idempotency UNIQUE(user_id, idempotency_key)
);
CREATE TABLE IF NOT EXISTS ai_project_document_file (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    relative_path VARCHAR(512) NOT NULL, original_name VARCHAR(255) NOT NULL,
    media_type VARCHAR(120), size_bytes BIGINT NOT NULL, content_hash VARCHAR(128) NOT NULL,
    declared_kind VARCHAR(40), status VARCHAR(40) NOT NULL, content_blob BLOB NOT NULL,
    document_id BIGINT, error_code VARCHAR(64), error_summary VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase29_file_path UNIQUE(batch_id, relative_path)
);
CREATE TABLE IF NOT EXISTS ai_project_document (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, file_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL, work_id BIGINT NOT NULL, document_kind VARCHAR(40) NOT NULL,
    active_generation_id BIGINT, relative_path VARCHAR(512) NOT NULL, title VARCHAR(255),
    classification_confidence DECIMAL(5,4), classification_reasons CLOB,
    content_hash VARCHAR(128) NOT NULL, normalized_content CLOB NOT NULL,
    metadata_json CLOB, status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase29_document_file_path UNIQUE(file_id, relative_path)
);
CREATE TABLE IF NOT EXISTS ai_project_document_generation (
    document_generation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL, batch_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL, work_id BIGINT NOT NULL, parser_version VARCHAR(64) NOT NULL,
    content_hash VARCHAR(128) NOT NULL, status VARCHAR(40) NOT NULL,
    section_count INT NOT NULL DEFAULT 0, indexed_section_count INT NOT NULL DEFAULT 0,
    lease_owner VARCHAR(128), lease_expires_at TIMESTAMP, heartbeat_at TIMESTAMP,
    fencing_token BIGINT NOT NULL DEFAULT 0, error_code VARCHAR(64), error_summary VARCHAR(1000),
    activated_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase29_document_generation UNIQUE(document_id, parser_version, content_hash)
);
CREATE TABLE IF NOT EXISTS ai_project_document_section (
    section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL, document_generation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    section_ordinal INT NOT NULL, title VARCHAR(255), section_kind VARCHAR(40) NOT NULL,
    start_offset INT NOT NULL, end_offset INT NOT NULL, content_hash VARCHAR(128) NOT NULL,
    content CLOB NOT NULL, canonical_chapter_no INT, ingest_job_id BIGINT,
    status VARCHAR(40) NOT NULL, metadata_json CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase29_section_ordinal UNIQUE(document_generation_id, section_ordinal)
);
CREATE TABLE IF NOT EXISTS ai_project_document_question (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    file_id BIGINT, document_id BIGINT, question_type VARCHAR(40) NOT NULL,
    prompt VARCHAR(500) NOT NULL, options_json CLOB, answer_json CLOB,
    status VARCHAR(30) NOT NULL, resolved_by BIGINT, resolved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS ai_project_document_batch_outbox (
    outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, event_type VARCHAR(40) NOT NULL, attempt INT NOT NULL,
    status VARCHAR(20) NOT NULL, attempt_count INT NOT NULL DEFAULT 0,
    payload CLOB, available_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP, last_error VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_phase29_batch_outbox UNIQUE(batch_id, event_type, attempt)
);
CREATE TABLE IF NOT EXISTS ai_project_entity_evidence (
    entity_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, project_id BIGINT NOT NULL, work_id BIGINT NOT NULL,
    entity_type VARCHAR(60) NOT NULL, document_id BIGINT NOT NULL,
    document_generation_id BIGINT NOT NULL, section_id BIGINT, status VARCHAR(30) NOT NULL
);

ALTER TABLE IF EXISTS ai_project_search_document ALTER COLUMN chapter_id SET NULL;
ALTER TABLE IF EXISTS ai_project_search_document ALTER COLUMN generation_id SET NULL;
ALTER TABLE IF EXISTS ai_project_search_document ALTER COLUMN chapter_version SET NULL;
ALTER TABLE IF EXISTS ai_project_search_document ADD COLUMN IF NOT EXISTS source_document_id BIGINT;
ALTER TABLE IF EXISTS ai_project_search_document ADD COLUMN IF NOT EXISTS document_generation_id BIGINT;
ALTER TABLE IF EXISTS ai_project_search_document ADD COLUMN IF NOT EXISTS section_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_project_search_document_generation_key
    ON ai_project_search_document(user_id, project_id, work_id, document_generation_id, document_key);
CREATE INDEX IF NOT EXISTS idx_ai_project_search_document_generation
    ON ai_project_search_document(document_generation_id, section_id, status);

ALTER TABLE IF EXISTS ai_project_vector_chunk ADD COLUMN IF NOT EXISTS document_id BIGINT;
ALTER TABLE IF EXISTS ai_project_vector_chunk ADD COLUMN IF NOT EXISTS document_generation_id BIGINT;
ALTER TABLE IF EXISTS ai_project_vector_chunk ADD COLUMN IF NOT EXISTS section_id BIGINT;
ALTER TABLE IF EXISTS ai_project_vector_chunk ADD COLUMN IF NOT EXISTS profile_type VARCHAR(40);
ALTER TABLE IF EXISTS ai_project_vector_chunk ADD COLUMN IF NOT EXISTS evidence_scope VARCHAR(40);
CREATE INDEX IF NOT EXISTS idx_ai_project_vector_document
    ON ai_project_vector_chunk(document_generation_id, section_id, status);
