package com.novelanalyzer.modules.knowledge;

import com.novelanalyzer.common.context.AuthUser;
import com.novelanalyzer.common.context.AuthUserHolder;
import com.novelanalyzer.common.exception.BusinessException;
import com.novelanalyzer.modules.knowledge.dto.ProjectKnowledgeFeedbackRequest;
import com.novelanalyzer.modules.knowledge.service.KnowledgeProjectFeedbackService;
import com.novelanalyzer.modules.knowledge.service.KnowledgeProjectService;
import com.novelanalyzer.modules.knowledge.vo.ProjectKnowledgeFeedbackVO;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class KnowledgeProjectFeedbackServiceTest {

    @AfterEach
    void clearAuth() {
        AuthUserHolder.clear();
    }

    @Test
    void shouldPersistPendingFeedbackWithoutWritingConfirmedMemory() throws Exception {
        JdbcTemplate jdbc = jdbc();
        jdbc.execute("create table ai_project(project_id bigint generated by default as identity primary key, user_id bigint not null, name varchar(200), description varchar(500), status varchar(30), created_at timestamp default current_timestamp, updated_at timestamp default current_timestamp)");
        runScript(jdbc, resolveResource("sql/phase26-project-retrieval-eval-observability-h2.sql"));
        jdbc.update("insert into ai_project(user_id, name, description, status) values(7, 'p', 'd', 'ACTIVE')");
        Long projectId = jdbc.queryForObject("select project_id from ai_project where user_id = 7", Long.class);
        AuthUserHolder.set(AuthUser.of(7L, "writer", Set.of("USER")));

        KnowledgeProjectFeedbackService service = new KnowledgeProjectFeedbackService(jdbc, new KnowledgeProjectService(jdbc));
        ProjectKnowledgeFeedbackRequest request = new ProjectKnowledgeFeedbackRequest();
        request.setWorkId(11L);
        request.setGenerationId(77L);
        request.setFeedbackType("recall_error");
        request.setTargetType("chapter");
        request.setTargetKey("chapter:12");
        request.setOldValueJson("{\"ranked\":\"noise\"}");
        request.setNewValueJson("{\"ranked\":\"chapter:12\"}");
        request.setEvidenceJson("{\"chapterId\":12}");
        request.setNotes("wrong recall");

        ProjectKnowledgeFeedbackVO created = service.submit(projectId, request);
        assertThat(created.getFeedbackId()).isNotNull();
        assertThat(created.getReviewStatus()).isEqualTo(KnowledgeProjectFeedbackService.STATUS_PENDING);

        Integer feedbackCount = jdbc.queryForObject("select count(*) from ai_project_knowledge_feedback", Integer.class);
        assertThat(feedbackCount).isEqualTo(1);
        String status = jdbc.queryForObject("select review_status from ai_project_knowledge_feedback", String.class);
        assertThat(status).isEqualTo("PENDING");

        Integer memoryConfirmed = 0;
        try {
            memoryConfirmed = jdbc.queryForObject(
                "select count(*) from ai_memory where status = 'CONFIRMED' and user_id = 7",
                Integer.class
            );
        } catch (Exception ignored) {
            memoryConfirmed = 0;
        }
        assertThat(memoryConfirmed).isEqualTo(0);

        ProjectKnowledgeFeedbackRequest illegal = new ProjectKnowledgeFeedbackRequest();
        illegal.setFeedbackType("SAVE_PROJECT_DECISION");
        illegal.setTargetType("MEMORY");
        illegal.setTargetKey("fact:1");
        illegal.setNewValueJson("{\"status\":\"CONFIRMED\"}");
        assertThatThrownBy(() -> service.submit(projectId, illegal))
            .isInstanceOf(BusinessException.class)
            .hasMessageContaining("confirmed memory");
    }

    private JdbcTemplate jdbc() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:feedback_" + System.nanoTime() + ";MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return new JdbcTemplate(dataSource);
    }

    private Path resolveResource(String classpathRelative) throws Exception {
        Path[] candidates = new Path[] {
            Path.of("src/test/resources").resolve(classpathRelative),
            Path.of("backend/src/test/resources").resolve(classpathRelative),
            Path.of("..", "src/test/resources").resolve(classpathRelative)
        };
        for (Path candidate : candidates) {
            if (Files.isRegularFile(candidate)) {
                return candidate.toAbsolutePath().normalize();
            }
        }
        var url = getClass().getClassLoader().getResource(classpathRelative.replace("\\", "/"));
        if (url != null) {
            return Path.of(url.toURI());
        }
        throw new java.nio.file.NoSuchFileException(classpathRelative);
    }

    private void runScript(JdbcTemplate jdbc, Path path) throws Exception {
        String sql = Files.readString(path, StandardCharsets.UTF_8);
        if (!sql.isEmpty() && sql.charAt(0) == '\ufeff') {
            sql = sql.substring(1);
        }
        for (String stmt : sql.split(";")) {
            StringBuilder cleaned = new StringBuilder();
            for (String line : stmt.split("\\R")) {
                if (!line.trim().startsWith("--")) {
                    cleaned.append(line).append('\n');
                }
            }
            String executable = cleaned.toString().trim();
            if (executable.isEmpty()) {
                continue;
            }
            try {
                jdbc.execute(executable);
            } catch (Exception ex) {
                String message = ex.getMessage() == null ? "" : ex.getMessage().toLowerCase();
                if (!message.contains("already exists") && !message.contains("duplicate")) {
                    throw ex;
                }
            }
        }
    }
}
